apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-management
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: misbah-argocd-lab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.17
      helm:
        releaseName: argocd
        valueFiles:
          - $values/platform/argocd/values.yaml
    - repoURL: https://github.com/mirkaay/akuity.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
